language: node_js

node_js:
- node

before_script:
  - yarn install

script:
  - yarn test

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: keboola/middy-error-logger
    branch: master
