name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set tag
        id: tag
        run: |
          TAG="${GITHUB_REF##*/}"
          IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
          echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
          echo "::set-output name=is_semantic_tag::$IS_SEMANTIC_TAG"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn test:lint

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test:unit

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/') && needs.build.outputs.is_semantic_tag == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
